/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MainLayoutRouteImport } from './app/_main/layout'
import { Route as MainIndexRouteImport } from './app/_main/index'
import { Route as MainauthRegisterRouteImport } from './app/_main/(auth)/register'
import { Route as MainauthLoginRouteImport } from './app/_main/(auth)/login'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainauthRegisterRoute = MainauthRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainauthLoginRoute = MainauthLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => MainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof MainauthLoginRoute
  '/register': typeof MainauthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof MainauthLoginRoute
  '/register': typeof MainauthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainLayoutRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/(auth)/login': typeof MainauthLoginRoute
  '/_main/(auth)/register': typeof MainauthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register'
  id:
    | '__root__'
    | '/_main'
    | '/_main/'
    | '/_main/(auth)/login'
    | '/_main/(auth)/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(auth)/register': {
      id: '/_main/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MainauthRegisterRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(auth)/login': {
      id: '/_main/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainauthLoginRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainauthLoginRoute: typeof MainauthLoginRoute
  MainauthRegisterRoute: typeof MainauthRegisterRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainauthLoginRoute: MainauthLoginRoute,
  MainauthRegisterRoute: MainauthRegisterRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
