/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MainLayoutRouteImport } from './app/_main/layout'
import { Route as MainIndexRouteImport } from './app/_main/index'
import { Route as MaingameGameModeRouteImport } from './app/_main/(game)/game-mode'
import { Route as MainauthRegisterRouteImport } from './app/_main/(auth)/register'
import { Route as MainauthLoginRouteImport } from './app/_main/(auth)/login'
import { Route as MaingameGameModeSinglePlayerRouteImport } from './app/_main/(game)/game-mode.single-player'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MaingameGameModeRoute = MaingameGameModeRouteImport.update({
  id: '/(game)/game-mode',
  path: '/game-mode',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainauthRegisterRoute = MainauthRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainauthLoginRoute = MainauthLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MaingameGameModeSinglePlayerRoute =
  MaingameGameModeSinglePlayerRouteImport.update({
    id: '/single-player',
    path: '/single-player',
    getParentRoute: () => MaingameGameModeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof MainauthLoginRoute
  '/register': typeof MainauthRegisterRoute
  '/game-mode': typeof MaingameGameModeRouteWithChildren
  '/game-mode/single-player': typeof MaingameGameModeSinglePlayerRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof MainauthLoginRoute
  '/register': typeof MainauthRegisterRoute
  '/game-mode': typeof MaingameGameModeRouteWithChildren
  '/game-mode/single-player': typeof MaingameGameModeSinglePlayerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainLayoutRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/(auth)/login': typeof MainauthLoginRoute
  '/_main/(auth)/register': typeof MainauthRegisterRoute
  '/_main/(game)/game-mode': typeof MaingameGameModeRouteWithChildren
  '/_main/(game)/game-mode/single-player': typeof MaingameGameModeSinglePlayerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/game-mode'
    | '/game-mode/single-player'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/game-mode' | '/game-mode/single-player'
  id:
    | '__root__'
    | '/_main'
    | '/_main/'
    | '/_main/(auth)/login'
    | '/_main/(auth)/register'
    | '/_main/(game)/game-mode'
    | '/_main/(game)/game-mode/single-player'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(game)/game-mode': {
      id: '/_main/(game)/game-mode'
      path: '/game-mode'
      fullPath: '/game-mode'
      preLoaderRoute: typeof MaingameGameModeRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(auth)/register': {
      id: '/_main/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MainauthRegisterRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(auth)/login': {
      id: '/_main/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainauthLoginRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(game)/game-mode/single-player': {
      id: '/_main/(game)/game-mode/single-player'
      path: '/single-player'
      fullPath: '/game-mode/single-player'
      preLoaderRoute: typeof MaingameGameModeSinglePlayerRouteImport
      parentRoute: typeof MaingameGameModeRoute
    }
  }
}

interface MaingameGameModeRouteChildren {
  MaingameGameModeSinglePlayerRoute: typeof MaingameGameModeSinglePlayerRoute
}

const MaingameGameModeRouteChildren: MaingameGameModeRouteChildren = {
  MaingameGameModeSinglePlayerRoute: MaingameGameModeSinglePlayerRoute,
}

const MaingameGameModeRouteWithChildren =
  MaingameGameModeRoute._addFileChildren(MaingameGameModeRouteChildren)

interface MainLayoutRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainauthLoginRoute: typeof MainauthLoginRoute
  MainauthRegisterRoute: typeof MainauthRegisterRoute
  MaingameGameModeRoute: typeof MaingameGameModeRouteWithChildren
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainauthLoginRoute: MainauthLoginRoute,
  MainauthRegisterRoute: MainauthRegisterRoute,
  MaingameGameModeRoute: MaingameGameModeRouteWithChildren,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
