/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MainLayoutRouteImport } from './app/_main/layout'
import { Route as MainIndexRouteImport } from './app/_main/index'
import { Route as MainuserUserPrivateProfileRouteImport } from './app/_main/(user)/user-private-profile'
import { Route as MaininfoLeaderboardRouteImport } from './app/_main/(info)/leaderboard'
import { Route as MaingameSinglePlayerRouteImport } from './app/_main/(game)/single-player'
import { Route as MaingameMultiplayerRouteImport } from './app/_main/(game)/multiplayer'
import { Route as MaingameGameModesRouteImport } from './app/_main/(game)/game-modes'
import { Route as MainauthRegisterRouteImport } from './app/_main/(auth)/register'
import { Route as MainauthLoginRouteImport } from './app/_main/(auth)/login'
import { Route as MainuserUsersIdRouteImport } from './app/_main/(user)/users.$id'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainuserUserPrivateProfileRoute =
  MainuserUserPrivateProfileRouteImport.update({
    id: '/(user)/user-private-profile',
    path: '/user-private-profile',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MaininfoLeaderboardRoute = MaininfoLeaderboardRouteImport.update({
  id: '/(info)/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MaingameSinglePlayerRoute = MaingameSinglePlayerRouteImport.update({
  id: '/(game)/single-player',
  path: '/single-player',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MaingameMultiplayerRoute = MaingameMultiplayerRouteImport.update({
  id: '/(game)/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MaingameGameModesRoute = MaingameGameModesRouteImport.update({
  id: '/(game)/game-modes',
  path: '/game-modes',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainauthRegisterRoute = MainauthRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainauthLoginRoute = MainauthLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainuserUsersIdRoute = MainuserUsersIdRouteImport.update({
  id: '/(user)/users/$id',
  path: '/users/$id',
  getParentRoute: () => MainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof MainauthLoginRoute
  '/register': typeof MainauthRegisterRoute
  '/game-modes': typeof MaingameGameModesRoute
  '/multiplayer': typeof MaingameMultiplayerRoute
  '/single-player': typeof MaingameSinglePlayerRoute
  '/leaderboard': typeof MaininfoLeaderboardRoute
  '/user-private-profile': typeof MainuserUserPrivateProfileRoute
  '/users/$id': typeof MainuserUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof MainauthLoginRoute
  '/register': typeof MainauthRegisterRoute
  '/game-modes': typeof MaingameGameModesRoute
  '/multiplayer': typeof MaingameMultiplayerRoute
  '/single-player': typeof MaingameSinglePlayerRoute
  '/leaderboard': typeof MaininfoLeaderboardRoute
  '/user-private-profile': typeof MainuserUserPrivateProfileRoute
  '/users/$id': typeof MainuserUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainLayoutRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/(auth)/login': typeof MainauthLoginRoute
  '/_main/(auth)/register': typeof MainauthRegisterRoute
  '/_main/(game)/game-modes': typeof MaingameGameModesRoute
  '/_main/(game)/multiplayer': typeof MaingameMultiplayerRoute
  '/_main/(game)/single-player': typeof MaingameSinglePlayerRoute
  '/_main/(info)/leaderboard': typeof MaininfoLeaderboardRoute
  '/_main/(user)/user-private-profile': typeof MainuserUserPrivateProfileRoute
  '/_main/(user)/users/$id': typeof MainuserUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/game-modes'
    | '/multiplayer'
    | '/single-player'
    | '/leaderboard'
    | '/user-private-profile'
    | '/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/game-modes'
    | '/multiplayer'
    | '/single-player'
    | '/leaderboard'
    | '/user-private-profile'
    | '/users/$id'
  id:
    | '__root__'
    | '/_main'
    | '/_main/'
    | '/_main/(auth)/login'
    | '/_main/(auth)/register'
    | '/_main/(game)/game-modes'
    | '/_main/(game)/multiplayer'
    | '/_main/(game)/single-player'
    | '/_main/(info)/leaderboard'
    | '/_main/(user)/user-private-profile'
    | '/_main/(user)/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(user)/user-private-profile': {
      id: '/_main/(user)/user-private-profile'
      path: '/user-private-profile'
      fullPath: '/user-private-profile'
      preLoaderRoute: typeof MainuserUserPrivateProfileRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(info)/leaderboard': {
      id: '/_main/(info)/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof MaininfoLeaderboardRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(game)/single-player': {
      id: '/_main/(game)/single-player'
      path: '/single-player'
      fullPath: '/single-player'
      preLoaderRoute: typeof MaingameSinglePlayerRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(game)/multiplayer': {
      id: '/_main/(game)/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MaingameMultiplayerRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(game)/game-modes': {
      id: '/_main/(game)/game-modes'
      path: '/game-modes'
      fullPath: '/game-modes'
      preLoaderRoute: typeof MaingameGameModesRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(auth)/register': {
      id: '/_main/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MainauthRegisterRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(auth)/login': {
      id: '/_main/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainauthLoginRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/(user)/users/$id': {
      id: '/_main/(user)/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof MainuserUsersIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainauthLoginRoute: typeof MainauthLoginRoute
  MainauthRegisterRoute: typeof MainauthRegisterRoute
  MaingameGameModesRoute: typeof MaingameGameModesRoute
  MaingameMultiplayerRoute: typeof MaingameMultiplayerRoute
  MaingameSinglePlayerRoute: typeof MaingameSinglePlayerRoute
  MaininfoLeaderboardRoute: typeof MaininfoLeaderboardRoute
  MainuserUserPrivateProfileRoute: typeof MainuserUserPrivateProfileRoute
  MainuserUsersIdRoute: typeof MainuserUsersIdRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainauthLoginRoute: MainauthLoginRoute,
  MainauthRegisterRoute: MainauthRegisterRoute,
  MaingameGameModesRoute: MaingameGameModesRoute,
  MaingameMultiplayerRoute: MaingameMultiplayerRoute,
  MaingameSinglePlayerRoute: MaingameSinglePlayerRoute,
  MaininfoLeaderboardRoute: MaininfoLeaderboardRoute,
  MainuserUserPrivateProfileRoute: MainuserUserPrivateProfileRoute,
  MainuserUsersIdRoute: MainuserUsersIdRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
